on: [push]
name: variable substitution in json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1 
      with:
        files: 'parseme.json'
      env:
        username: chimpanda
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}
    - run: |
       cat parseme.json
    
