on: [push]
name: variable substitution in json

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1 
      with:
        files: 'parseme.json'
      env:
        AppSettings.Token: ${{ secrets.APPSETTINGS_TOKEN }}
        AppSettings.CipherPassPhrase: ${{ secrets.APPSETTINGS_CIPHERPASSPHRASE }}
        ConnectionStrings.MySqlConnection: ${{ secrets.CONNECTIONSTRING }}
        SendInBlue.ApiKey: ${{ secrets.SENDINBLUE_APIKEY }}
        AmazonS3.AccessKeyId: ${{ secrets.AMAZONS3_ACCESSKEYID }}
        AmazonS3.SecretAccessKey: ${{ secrets.AMAZONS3_SECRETACCESSKEY}}
    - name: catting file
    - run: |
       cat parseme.json
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./parseme.json
    - name: Echo parseme.json
      run: echo "${{ steps.package.outputs.content }}"
       
