on: [push]
name: variable substitution in json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1 
      with:
        files: 'parseme.json'
      env:
        AppSettings.Token: ${{ secrets.APPSETTINGS_TOKEN }}
        AppSettings.CipherPassPhrase: ${{ secrets.APPSETTINGS_CIPHERPASSPHRASE }}
        ConnectionStrings.MySqlConnection: ${{ secrets.CONNECTIONSTRING }}
        SendInBlue.ApiKey: ${{ secrets.SENDINBLUE_APIKEY }}
        AmazonS3.AccessKeyId: ${{ secrets.AMAZONS3_ACCESSKEYID }}
        AmazonS3.SecretAccessKey: ${{ secrets.AMAZONS3_SECRETACCESSKEY}}
    - run: |
       cat parseme.json
